mybank/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls", namespace="users")),

]

users/urls.py
from django.urls import path
from users.views import LoginView, Logout, CreateUser, LandingPage

app_name = "users"


urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("create-account", CreateUser.as_view(), name="create_user"),
    path("logout", Logout, name="logout"),
    path("home", LandingPage.as_view(), name="landing"),

]

users/models.py
import uuid
import datetime as d

from django.db import models
from django.dispatch import receiver
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.db.models import Sum


class UserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_staff", True)

        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(
        unique=True, help_text="A confirmation message would be sent to your Email"
    )
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)


    class Meta(object):
        unique_together = ("email",)

    USERNAME_FIELD = "email"
    objects = UserManager()

    REQUIRED_FIELDS = ["first_name", "last_name"]

    def full_name(self):
        return "{}".format(self.email )



        # return "{} {} {}".format(self.first_name, self.last_name, )

    def __str__(self):
        return str(self.full_name())




class Account_Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    account_number = models.CharField(max_length=300, null=True, blank=True)
    account_type = models.CharField(max_length=300, null=True, blank=True)
    country = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=300, null=True, blank=True)
    phone_number = models.CharField(max_length=300, null=True, blank=True)
    address = models.CharField(max_length=300, null=True, blank=True)
    sms = models.BooleanField(default=False)
    email = models.BooleanField(default=False)
    internet_banking_id = models.CharField(max_length=100, null=True, blank=True)
    account_balance = models.DecimalField(max_digits=6, decimal_places=2)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    # _account_type = (                          #private attributes
    #       ('tier_one', 'Tier_one'),
    #       ('Ttier_two', 'Tier_two'),
    #       ('Ttier_three', 'Tier_three'),
          
    # )
    # account_type  = models.CharField(max_length=100, choices= _account_type)
 

    def __str__(self):
        return self.user.email

    class Meta:
        verbose_name_plural = "Profiles"

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import User, Account_Profile
from random import randint


class LandingPage(View):
    def get(self, request):
        template_name = "users/landingpage.html"
        
        return render(request, template_name, context={})
        



class LoginView(View):
    def get(self, request):
        template_name = "users/login.html"
        if request.user.is_authenticated:
            return redirect("users:landing")
        return render(request, template_name, context={})
        

    def post(self, request):
        username = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        print(user)
        if user is not None:
            print('user exists')

            if user.is_active:
                print('user is active')

                login(request, user)
                print('logged in')
                return redirect("users:landing")
                
            else:
                messages.error(request, "Your account has been disabled.")
                return redirect("users:login")
        else:
            messages.error(request, "Invalid login credentials.")
            return redirect("users:login")
        



class CreateUser(View):
    def get(self, request):
        template_name = "users/createuser.html"
        if request.user.is_authenticated:
            return redirect("users:dashboard")
        return render(request, template_name, context={})


    def post(self, request):
        email = request.POST["email"]
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]

        # account_number = request.POST["account_number"] this should be automatically generated
        account_type = request.POST["account_type"]
        country = request.POST["country"]
        state = request.POST["state"]
        address = request.POST["address"]
        phone_number = request.POST["phone_number"]
        # sms = request.POST["sms"]
        # email = request.POST["email"]
        # internet_banking_id = request.POST["internet_banking_id"] this should be automatically generated
        password = request.POST["password"]
        account_balance = request.POST["account_balance"]
        account_number = randint(10000000000, 100000000000)
        internet_banking_id = randint(111111, 999999)

        if not User.objects.filter(email=email).exists():
            created_user = User.objects.create(
                first_name=first_name, last_name=last_name, email=email
            )
            created_user.set_password(password)
            created_user.save()
            print(created_user)
            Account_Profile.objects.create(user=created_user, account_number=account_number,
            account_type=account_type,
            country=country,
            # city=city,
            phone_number=phone_number,
            address=address,
            # sms=sms,
            # email=email,
            account_balance=account_balance,
            internet_banking_id=internet_banking_id,)
            messages.success(request, "Account Created successfully. login to approve account and start banking with us")
            return redirect("users:login")
        else:
            messages.error(request, "user with email already exist")
            return redirect("users:create_user")






def Logout(request):
    logout(request)
    return redirect("users:login")

templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Plus Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="../../../assets/vendors/mdi/css/materialdesignicons.min.css">

    <!-- Layout styles -->
    <link href="{% static 'css/demo_2/style.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="../../../assets/css/demo_2/style.css" />
    <!-- End layout styles -->
    <link rel="shortcut icon" href="../../../assets/images/favicon.png" />
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

      
    
      {% block content %}

      {% endblock content %}
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- <link href="{% static 'css/demo_2/style.css' %}" rel="stylesheet"> -->


    <script src="{% static 'js/js/vendor.bundle.base.js' %}"></script>
    <script src="{% static 'js/settings.js' %}"></script>


    <!-- <script src="{% static 'js/demo_2/style.css' %} ../../../assets/js/settings.js"></script> -->


  </body>
</html>

templates/users/createuser.html
{% load static %}
<!--<!DOCTYPE html> -->
<html lang="en-US">

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Loginto fast bankin</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    </head>
    <body>
       <div class="">
        <div class="">
          <div class="container text-center">
            <h1 style="padding: 30px 0px; color: rgb(255, 145, 0);"><a style="color: rgb(255, 145, 0);" href='/' >Fast Banking</a></h1>
        </div>
      <div class="container ">
    <div class="row ">
      
      <form method="POST" class="col-md-6 offset-md-4">
        {% csrf_token %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
            </div>
            {% endfor %}
        {% endif %}
          <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input required name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
          </div>

          <div class="form-group">
            <label for="first_name">First name</label>
            <input required name="first_name" type="text" class="form-control" id="first_name" aria-describedby="emailHelp">
          </div>
          <div class="form-group">
            <label for="last_name">Last name</label>
            <input required name="last_name" type="text" class="form-control" id="last_name" aria-describedby="emailHelp">
          </div>


          <div class="form-group">
    <label for="exampleFormControlSelect1">Account Type</label>
    <select class="form-control" id="exampleFormControlSelect1" name="account_type" id="account_type">
      <option value='tier_one'>Tier one</option>
      <option value='Ttier_two'>Tier two</option>
      <option value='Ttier_three'>Tier three</option>

    </select>
  </div>


          <div class="form-group">
    <label for="exampleFormControlSelect1">Country</label>
    <select class="form-control" id="exampleFormControlSelect1" name="country" id="country">
      <option value='Nigeria'>Nigeria </option>
      <option value='Ghana'>Ghana </option>
      <option value='Benin'>Benin </option>

    </select>
  </div>

                    <div class="form-group">
            <label for="state">State</label>
            <input required name="state" type="text" class="form-control" id="state" aria-describedby="emailHelp">
          </div>
                    <div class="form-group">
            <label for="address">Full Address</label>
            <input required name="address" type="text" class="form-control" id="address" aria-describedby="emailHelp">
          </div>

                    <div class="form-group">
            <label for="phone_number">phone Number</label>
            <input required name="phone_number" type="number"  class="form-control" id="phone_number" aria-describedby="emailHelp">
          </div>


                  <div class="form-group">
            <label for="account_balance">Open Account with</label>
            <input required name="account_balance" type="number" min="1" step="any" class="form-control" id="account_balance" aria-describedby="emailHelp">
          </div>



          <div class="form-group">
            <label for="password">Password</label>
            <input required name='password' type="password" class="form-control" id="password">
          </div>
          
          <button type="submit" class="btn btn-warning text-white btn-block">Create Bank Account</button>
        </form>
        </div>
      </div>
        </div>
       </div>
      
    </body>
</html>

templates/users/landingpage.html
{% load static %}

<!--<!DOCTYPE html> -->
<html lang="en-US">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"><!-- displays site properly based on user's device -->

  <link rel="icon" type="image/png" sizes="32x32" href="./images/favicon-32x32.png">

  <meta name="author" content="Anuj Yadav">
  <meta name="description" content="Easybank landing page using bootstrap 4, a challenge by frontendmentor.io">
  <meta name="keywords" content="Easybank, landing page, frontendmentor">
  <title> Easybank landing page | Frontend Mentor</title>
  <style>
    
  </style>
    <link href="{% static 'css/easy_style.css' %}" rel="stylesheet">


</head>

<body>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0, minimum-scale=1, maximum-scale=1">
  <div id="page-wrapper">
  <header id="header">
   <div class="logo">
      <h1 style="color: orange;">Fast Banking</h1>
    </div>
    <nav id="nav-bar">
      <form id="form" action="https://www.freecodecamp.com/email-submit">
        <input name="email" id="email" type="email" placeholder="Enter your email.." required/>
        <input id="submit" type="submit" value="Subscribe" class="btn1"</input>
        </nav></form>


      <ul>
        {% if request.user.is_authenticated %}
        <li>welcome, {{request.user.first_name}}</li>
        <li>{{request.user.get_account_profile.account_number}}</li>
        <li><a class="nav-link" href="{% url 'users:logout' %}">logout</a></li>



        {% else %}
        
        <li><a class="nav-link" href="/login">login</a></li>
        <li><a class="nav-link" href="/create-account">create free account with us</a></li>
        <li><a class="nav-link" href="#pricing">contact us</a></li>
        {% endif %}
      </ul>  
    </nav>
  </header>
    
  
    <div class="container">
    
     <div class="start"> 
      <h1 id="headline">Borderless payments in a borderless world.</h1> 
      <section id="intro">      
        <img src="https://raw.githubusercontent.com/FesoQue/Easybank-landing-page/master/images/image-mockups.png" class="mockup" alt="mockup">       </section></div>      
     <section id="features">
       <div class="grid">
       <h3 id="gridh3">Next generation digital banking</h3>        <div class="left">        
         <p id="paragraph">Take your financial life online. Your Easybank account will be a one-stop-shop for spending, saving, budgeting, investing, and much more..</p>
         <ul class="list">
          <li><img class="icon" src="https://bitcoin.org/img/icons/main_ico_instant.svg?1540649158"/>
          <div class="desc">
            <p>Our modern web and mobile applications allow you to keep track of your finances wherever you are in the world.
            </p>
            </div></li>
          <li><img class="icon" src="https://bitcoin.org/img/icons/main_ico_worldwide.svg?1540649158"/>
          <div class="desc">
            <p>See exactly where your money goes each month. Receive notifications when you’re close to hitting your limits.</p>
            </div></li>
          <li><img class="icon" src="https://bitcoin.org/img/icons/main_ico_lowfee.svg?1540649158"/>
          <div class="desc">
            <p>We don’t do branches. Open your account in minutes online and start taking control of your finances right away.</p>
            </div></div></li></ul>
          <img class="btc" src="https://bitcoin.org/img/home/bitcoin-img.svg?1540649158"/>
          </div>     
       </div>
     </section>



  <div class="bg-image">
     <section id="developments">
        <h3 id="ftrs">Features</h3>  
       <div id="decentralized">
         <div class="title">
           <h2>online banking
          </h2>
           <h2>∞</h2></div>
          <ol class="ol">
           
          </ol>
         <button class="btn">Learn more</button>
       </div>
       <div id="segwit">
         <div class="title">
           <h2>Simple Budgeting
          </h2>
         
         <h2>∞</h2></div>
          <ol class="ol">
          
          </ol>
         <button class="btn">Learn more</button>
       </div>
        <div id="lightning">
         <div class="title">
           <h2>Fast Onboarding
          </h2>
         
         <h2>∞</h2></div>
          <ol class="ol">
      
          </ol>
         <button class="btn">Learn more</button>
       </div>
       <div id="lightning">
        <div class="title">
          <h2>Open API
          </h2>
        
        <h2>∞</h2></div>
         <ol class="ol">
          
         </ol>
        <button class="btn">Learn more</button>
      </div>
    </section></div>
   
      <footer>
        <ul id="footerul">
          <li class="footerli"> <a href="">Privacy</li></a>
          <li class="footerli"> <a href="">Terms</li></a>
          <li class="footerli"> <a href="">Contact</li></a>
          <li class="footerli"> <a href="#intro">↑</li></a>
          <li class="footerli"> <a href="">ⓕ</li></a>
          <li class="footerli"> <a href="">ⓣ</li></a>       
        </ul>
        <span>© Adrian S.</span>
      </footer>
    </div>
</body>

</html>

templates/users/login.html
{% load static %}
<!--<!DOCTYPE html> -->
<html lang="en-US">

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Loginto fast bankin</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    </head>
    <body>
       <div class="">
        <div class="">
          <div class="container text-center">
            <h1 style="padding: 30px 0px; color: rgb(255, 145, 0);"><a style="color: rgb(255, 145, 0);" href='/' >Fast Banking</a></h1>
        </div>
      <div class="container ">
    <div class="row ">
      
      <form method="POST" class="col-md-6 offset-md-4">
        {% csrf_token %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
            </div>
            {% endfor %}
        {% endif %}


        <div class="alert alert-success" role="alert">
Login to start banking with us</div>
          <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input name='password' type="password" class="form-control" id="exampleInputPassword1">
          </div>
          
          <button type="submit" class="btn btn-warning text-white btn-block">Login</button>
        </form>
        </div>
      </div>
        </div>
       </div>
      
    </body>
</html>

templates/users/loginform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <title>Document</title>
    <style>
        
    </style>
</head>
<body>
    <form class="form" action="index.html" method="post">
        <h1> Sign Up </h1>
        
        <fieldset>
          
          <legend><span class="number">1</span> Your Basic Info</legend>
        
          <label for="name">Name:</label>
          <input type="text" id="name" name="user_name">
        
          <label for="email">Email:</label>
          <input type="email" id="mail" name="user_email">
       
          <label for="password">Password:</label>
          <input type="password" id="password"       name="user_password">
        
          <label>Age:</label>
          <input type="radio" id="under_13" value="under_13" name="user_age"><label for="under_13" class="light">Under 13</label><br>
          <input type="radio" id="over_13" value="over_13" name="user_age"><label for="over_13" class="light">Over 13</label>
          
        </fieldset>
        <fieldset>  
        
          <legend><span class="number">2</span> Your Profile</legend>
          
         <label for="bio">Bio:</label>
          <textarea id="bio" name="user_bio"></textarea>
        
       
        
         <label for="job">Job Role:</label>
          <select id="job" name="user_job">
            <optgroup label="Web">
              <option value="frontend_developer">Front-End Developer</option>
              <option value="php_developer">PHP Developer</option>
              <option value="python_developer">Python Developer</option>
              <option value="rails_developer">Rails Developer</option>
              <option value="web_designer">Web Designer</option>
              <option value="wordpress_developer">Wordpress Developer</option>
            </optgroup>
            <optgroup label="Mobile">
              <option value="android_developer">Android Developer</option>
              <option value="ios_developer">IOS Developer</option>
              <option value="mobile_designer">Mobile Designer</option>
            </optgroup>
            <optgroup label="Business">
              <option value="business_owner">Business Owner</option>
              <option value="freelancer">Freelancer</option>
            </optgroup>
          </select>
          
          <label>Interests:</label>
          <input type="checkbox" id="development" value="interest_development" name="user_interest"><label class="light" for="development">Development</label><br>
          <input type="checkbox" id="design" value="interest_design" name="user_interest"><label class="light" for="design">Design</label><br>
          <input type="checkbox" id="business" value="interest_business" name="user_interest"><label class="light" for="business">Business</label>
          
         </fieldset>
       
        <button type="submit">Sign Up</button>
        
       </form>  
</body>
</html>